apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-worker
  namespace: task-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: task-worker

  template:
    metadata:
      labels:
        app: task-worker

    spec:
      containers:
      - name: task-worker
        image: task-worker:2.0
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: REDIS_HOST

        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: task-config
              key: REDIS_PORT
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1