name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build API Image
      run: |
        docker build -t task-api:latest -f services/api/Dockerfile .

    - name: Build Worker Image
      run: |
        docker build -t task-worker:latest -f services/worker/Dockerfile .